// Codegen: scan the baked satellite PNGs and emit src/ui/satelliteManifest.ts — the per-key
// TilesetAsset list the registry layers over the procedural atlas. One file per atlas key (the
// controlnet bake is per-key: each band/pos/tier diffused from its own procedural structure, so
// tier-1 decay ≠ tier-0 pristine, edge cell ≠ center). Idempotent — re-run after every bake.
//
//   node tools/tileset/manifest.mjs
import { readdirSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '../..');
const ROOT = join(REPO, 'public/tilesets/satellite');
const SUBDIRS = ['terrain', 'buildings']; // diffused full-tile categories (roads stay surface+procedural)

const entries = [];
for (const sub of SUBDIRS) {
  const dir = join(ROOT, sub);
  if (!existsSync(dir)) continue;
  for (const f of readdirSync(dir).filter((f) => f.endsWith('.png')).sort()) {
    // PlantedMedian (kind 11) must render as the PROCEDURAL green strip (it forms a connected line) —
    // NOT a baked building tile. Skip its baked cells so the tileset doesn't override the painter.
    if (/^b-11-/.test(f)) continue;
    // A `-v{n}` suffix is a building VARIANT — map it to the variantKey form `{base}#{n}` the
    // renderer picks per parcel (generate-variants.mjs). Plain files map to their key 1:1.
    const stem = f.replace(/\.png$/, '');
    const v = /^(.+)-v(\d+)$/.exec(stem);
    entries.push({ file: `${sub}/${f}`, key: v ? `${v[1]}#${v[2]}` : stem });
  }
}

const lines = entries.map((e) => `  { file: '${e.file}', keys: ['${e.key}'] },`).join('\n');
const out = `// AUTO-GENERATED by tools/tileset/manifest.mjs — do not edit by hand.
// The committed satellite-tileset PNGs, one file per atlas key (band / building pos+tier),
// generated through the Z-Image Tile-ControlNet pipeline (docs/art/satellite-tileset.md §5.6).
// Regenerate after a bake: \`node tools/tileset/manifest.mjs\`. Pure data — no DOM, no Math.
import type { TilesetAsset } from './tileset';

export const SATELLITE_BAKED: readonly TilesetAsset[] = [
${lines}
];
`;
writeFileSync(join(REPO, 'src/ui/satelliteManifest.ts'), out);
console.log(`wrote src/ui/satelliteManifest.ts with ${entries.length} baked tiles`);
