// Worldgen pipeline abstraction.
//
// A world is generated by running an ordered list of stages over a shared
// WorldState. Each stage receives its own rng stream forked from the root
// seed *by the stage's name* — so the stream a stage sees depends only on
// (seed, stage name), never on which sibling stages ran before it. That is
// the determinism contract that lets us insert or remove a stage without
// perturbing the rest of the world (DF-style reproducibility).

import { GameMap } from '../engine/map';
import { ParcelStore } from '../engine/fabric';
import { createRng, type Rng } from '../engine/rng';

export interface WorldState {
  map: GameMap;
  /**
   * Building-parcel attributes (kind/density/condition). Combined with `map`
   * via {@link hashWorld} (engine/fabric) — THE canonical world hash for every
   * stage determinism test from now on. `map.snapshot()` alone is insufficient
   * once a stage mutates parcel attributes, which live here, not on the map.
   */
  parcels: ParcelStore;
  seed: string;
  log: string[];
}

export interface WorldgenStage {
  /** Unique stage name; also keys the stage's forked rng stream. */
  name: string;
  apply(world: WorldState, rng: Rng): void;
}

export interface RunPipelineOptions {
  seed: string;
  width?: number;
  height?: number;
}

export function runPipeline(opts: RunPipelineOptions, stages: WorldgenStage[]): WorldState {
  const map = new GameMap(opts.width, opts.height);
  const world: WorldState = { map, parcels: new ParcelStore(), seed: opts.seed, log: [] };
  const rootRng = createRng(opts.seed);

  for (const stage of stages) {
    stage.apply(world, rootRng.fork(stage.name));
    world.log.push(stage.name);
  }

  return world;
}
